apiVersion: v1
kind: Service
metadata:
  name: diabetes-app-svc
  namespace: mlops-diabetes
spec:
  type: NodePort
  selector:
    app: diabetes-app
  ports:
    - name: api
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: ui
      port: 8501
      targetPort: 8501
      nodePort: 30081
