apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-service
  labels:
    app: diabetes-api

spec:
  type: NodePort                 
  selector:
    app: diabetes-api            
  ports:
    - name: http
      port: 8000                 
      targetPort: 8000          
      nodePort: 30080      

    - name: streamlit
      port: 8501
      targetPort: 8501
      nodePort: 30081       
